# Generated by Django 4.0.1 on 2022-01-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='What do you meme by that?', max_length=255),
        ),
    ]
