# Generated by Django 4.0.1 on 2022-01-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Blog Post...', max_length=255),
        ),
    ]
