# Generated by Django 4.0.1 on 2022-01-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeblog', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
